import {StyleSheet} from 'react-native';
export default Styles = StyleSheet.create({
  outsideContainer: {
    height: '70%',
    width: '90%',
    alignSelf: 'center',
  },
  backgroundStyles: {
    alignSelf: 'center',
    width: '100%',
    height: '100%',
    borderRadius: 10,
  },
  leftDrawingsStyle: {
    position: 'absolute',
    width: '90%',
    height: '100%',
    justifyContent: 'flex-end',
  },
  rightDrawingStyles: {
    alignSelf: 'flex-end',
    alignItems: 'flex-end',
    width: '70%',
    height: '60%',
  },
  fullCardView: {
    height: '100%',
    width: '100%',
    position: 'absolute',
    flexDirection: 'column',
  },
  topView: {
    height: '50%',
    width: '100%',
    flexDirection: 'row',
  },
  imageView: {
    height: '100%',
    width: '35%',
    justifyContent: 'center',
  },
  image: {
    marginLeft: 10,
    alignSelf: 'center',
    height: '80%',
    borderRadius: 130 / 2,
    width: '80%',
    backgroundColor: 'transparent',
    borderWidth: 5,
    borderColor: '#BFD0F7',
  },
  companyView: {
    flexDirection: 'row',
    marginTop: 15,
    marginRight: 15,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  companyText: {
    marginRight: 15,
    fontFamily: 'Nunito-Regular',
    color: 'white',
    fontSize: 12,
  },
  bottomView: {
    height: '50%',
    width: '100%',
    flexDirection: 'row',
  },
  fullInfoView: {
    height: '100%',
    width: '50%',
    justifyContent: 'center',
    paddingLeft: 20,
  },
  infoView: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  infoText: {
    marginLeft: 10,
    fontFamily: 'Nunito-Regular',
    color: 'white',
    fontSize: 12,
  },
  nameText: {
    marginLeft: 10,
    fontFamily: 'Nunito-SemiBold',
    color: 'white',
    fontSize: 16,
  },
  logoView: {
    height: '100%',
    width: '50%',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
});
